[package]
name = "lemmy_routes"
version = "0.12.0-rc.1"
edition = "2018"
description = "A link aggregator for the fediverse"
license = "AGPL-3.0"

[lib]
doctest = false

[dependencies]
lemmy_utils = { version = "=0.12.0-rc.1", path = "../utils" }
lemmy_websocket = { version = "=0.12.0-rc.1", path = "../websocket" }
lemmy_db_queries = { version = "=0.12.0-rc.1", path = "../db_queries" }
lemmy_db_views = { version = "=0.12.0-rc.1", path = "../db_views" }
lemmy_db_views_actor = { version = "=0.12.0-rc.1", path = "../db_views_actor" }
lemmy_db_schema = { version = "=0.12.0-rc.1", path = "../db_schema" }
lemmy_api_common = { version = "=0.12.0-rc.1", path = "../api_common" }
lemmy_apub_lib = { version = "=0.12.0-rc.1", path = "../apub_lib" }
diesel = "1.4.7"
actix = "0.12.0"
actix-web = { version = "4.0.0-beta.8", default-features = false, features = ["rustls"] }
actix-web-actors = { version = "4.0.0-beta.6", default-features = false }
actix-http = "3.0.0-beta.9"
sha2 = "0.9.5"
log = "0.4.14"
anyhow = "1.0.43"
chrono = { version = "0.4.19", features = ["serde"] }
rss = "1.10.0"
serde = { version = "1.0.129", features = ["derive"] }
awc = { version  = "3.0.0-beta.7", default-features = false }
url = { version = "2.2.2", features = ["serde"] }
strum = "0.21.0"
lazy_static = "1.4.0"
